apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-ui.fullname" . }}-secret
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.secrets.clientSecret | b64enc }}