apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convert.fullname" . }}-secret
  labels:
    {{- include "convert.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.secrets.clientSecret | b64enc }}