server:
  port: ${services.front-ui.port}

spring:
  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Cloud
  cloud:
    # Zookeeper
    zookeeper:
      discovery:
        enabled: true
      connect-string: zookeeper:2181

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/bankapp/protocol/openid-connect/token
            authorization-uri: http://keycloak:8080/realms/bankapp/protocol/openid-connect/auth
            jwk-set-uri: http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs
        registration:
          bankapp-client:
            client-id: bankapp-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    mode: HTML

# Circuit Breaker
resilience4j:
  retry:
    instances:
      gateway-service:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      gateway-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s