apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications.fullname" . }}-secret
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.secrets.clientSecret | b64enc }}
  db-password: {{ .Values.secrets.dbPassword | b64enc }}